### ISSUE TITLE
圓餅圖文字顯示

### ISSUE THREAD

**Issue by yhsiang** [g0v/twly-voter-guide#20]
解法1.
%數目大的留下文字顯示
小於一定比例就改成hover顯示
因為通常會擠在一起的都是小%數
如果有特別想知道是那些再用hover事件顯示就好

解法2.
文字改成用legend
legend跟圓餅部分做mouse interaction

**Comment by thewayiam** [comment]
[呈現效果](http://vote.ly.g0v.tw/legislator/personal_political_contributions/515/8/)
