### ISSUE TITLE
希望整合立委的"政治獻金 api "、"立委介紹api"

### ISSUE THREAD

**Issue by irisshu** [g0v/twly-voter-guide#25]
不知道能不能在原本"立委資料"的api 中，
(https://twly.herokuapp.com/api/legislator_terms/?page=1&ad=8)
加入政治獻金的資料，
(http://vote.ly.g0v.tw/api/political_contributions/)

例如將下列資訊跟"立委資料"結合在一起 :
           "in_individual": 27955099, 
            "in_profit": 25300000, 
            "in_party": 3000000, 
            "in_civil": 480000, 
            "in_anonymous": 8100, 
            "in_others": 13882, 
            "in_total": 56757081, 
            "out_personnel": 2562050, 
            "out_propagate": 5086177, 
            "out_campaign_vehicle": 0, 
            "out_campaign_office": 285000, 
            "out_rally": 0, 
            "out_travel": 199643, 
            "out_miscellaneous": 3861808, 
            "out_return": 1270000, 
            "out_exchequer": 1000000, 
            "out_public_relation": 83500, 
            "out_total": 14348178, 

這樣我可能會比較方便對應放入app中，非常感謝協助 ^_^

**Comment by thewayiam** [comment]
在立委個人api 加入提案、表決、出缺席紀錄
```json
[
    "bill_param": {
        "petition": 273, 
        "chief": 58, 
        "total": 469, 
        "proposal": 138
    }, 
    "vote_param": {
        "disagree": 246, 
        "conflict": 12, 
        "total": 405, 
        "not_voting": 63, 
        "agree": 95, 
        "abstain": 1
    }, 
    "attendance_param": {
        "total": 106, 
        "absent": 1
    }
]
```
