### ISSUE TITLE
希望可以用立委本身的ID存取到表決記錄、提案記錄的API

### ISSUE THREAD

**Issue by billy3321** [g0v/twly-voter-guide#28]
目前可以透過

http://vote.ly.g0v.tw/api/legislator_terms/?legislator=515

來找到丁守中的政治獻金連結

http://vote.ly.g0v.tw/api/candidates/413/

但裡面卻沒有以立委為單位分類出表決記錄、提案記錄。
希望可以加上這個功能，查詢到單一立委的表決、提案記錄，謝謝。

**Comment by yhsiang** [comment]
以段宜康為例子
表決紀錄
http://vote.ly.g0v.tw/api/legislator_vote/?legislator=1519
提案紀錄
http://localhost:8000/api/legislator_bill/?legislator=1519

http://vote.ly.g0v.tw/api/legislator_terms/1519 第 8 屆段宜康資料
http://localhost:8000/api/legislator/917/ 包含了所有屆數資料

**Comment by thewayiam** [comment]
https://github.com/g0v/twly-voter-guide/pull/29
Thanks to @yhsiang 
Now we could use id of each legislator in legislator_terms to query votes, bills
e.g. 
http://vote.ly.g0v.tw/api/legislator_terms/585/
http://vote.ly.g0v.tw/api/legislator_vote/?legislator=585

**Comment by billy3321** [comment]
感謝兩位！
