### ISSUE TITLE
legislator_vote 無法查詢「未投票」

### ISSUE THREAD

**Issue by billy3321** [g0v/twly-voter-guide#30]
以廖正井為例，第40頁可看到廖正井投票有部分未投票

http://vote.ly.g0v.tw/api/legislator_vote/?legislator=2357&page=40

```
{
    "url": "http://vote.ly.g0v.tw/api/legislator_vote/128274/", 
    "legislator": "http://vote.ly.g0v.tw/api/legislator_terms/2357/", 
    "vote": "http://vote.ly.g0v.tw/api/vote/985/", 
    "decision": null, 
    "conflict": null
}
```
可是若以null查詢投票記錄，卻會出錯
http://vote.ly.g0v.tw/api/legislator_vote/?legislator=2357&decision=null

這邊有辦法做修正嗎？謝謝。

**Comment by billy3321** [comment]
https://github.com/billy3321/twly-voter-guide/commit/d5c150d2caedb67c0bdd9fb7faa449dd53e5206e

嘗試動手做了一點修正，但電腦似乎還跑不起來，不知道驗證結果為何。

**Comment by billy3321** [comment]
好像不太能run....我再找找原因好了＠＠

**Comment by thewayiam** [comment]
Thanks to find the problems, please search like:
http://vote.ly.g0v.tw/api/legislator_vote/?legislator=2357&not_voting=True
