### ISSUE TITLE
Login/Logout function appears at the same time

### ISSUE THREAD

**Issue by ChenYoyo** [g0v/twly-voter-guide#33]
The color of Login/Logout is not consistent with other items on menu.

![1](https://cloud.githubusercontent.com/assets/2658643/7399017/6d76b9fc-eee5-11e4-8d55-1def95346a35.jpg)

**Comment by thewayiam** [comment]
有考慮把這個地方的登入/登出拿掉
目前只有在個別的單一表決頁有需要登入，例如 http://vote.ly.g0v.tw/vote/08-06-YS-17-001/
如果使用者想輸入標籤或投票+1再跳到登入頁就好

**Comment by thewayiam** [comment]
如上述
