### ISSUE TITLE
臺南市市徽更正

### ISSUE THREAD

**Issue by kagami3421** [g0v/twly-voter-guide#44]
臺南已更換市徽有半年了，請更正

**Comment by thewayiam** [comment]
[臺南市市徽下載連結](http://www.tainan.gov.tw/tainan/download.asp?nsub=G1A400)

**Comment by ETBlue** [comment]
檔案： https://drive.google.com/file/d/0B0NsS2a-Qx8ZYzFWWTVya1lweHc/view?usp=sharing
（原本資料夾位置在 https://drive.google.com/folderview?id=0B0NsS2a-Qx8ZeTA0MlRBdnVqMDQ&usp=sharing ，隔壁指南的資料夾裡那份，是複製的，我先放在原始的～）

![2015](https://cloud.githubusercontent.com/assets/244354/12083263/8bc75222-b2da-11e5-8708-d255e474408c.png)

**Comment by thewayiam** [comment]
已上傳，cache 也更新了，感謝回饋，感恩etblue

**Comment by noracami** [comment]
hello,
澎湖縣的目前也沒有上線，可以幫忙更新嗎
[縣徽from wiki](https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Seal_of_Penghu_County.svg/320px-Seal_of_Penghu_County.svg.png)

**Comment by thewayiam** [comment]
@noracami : 已更新，正要來學怎麼把背景變透明才發現你貼的已經是了，謝謝哦
