### ISSUE TITLE
手機版網頁，選單無法顯示

### ISSUE THREAD

**Issue by mark86092** [g0v/twly-voter-guide#46]
選單在視窗寬度縮小時會隱藏起來，但無法透過 .btn-navbar 的按鈕切換顯示隱藏

可能問題：[templates/base.html#L58](https://github.com/g0v/twly-voter-guide/blob/master/templates/base.html#L58) 當中每個選單都有套用 class `visible-desktop`

bootstrap-responsive.min.css 當中的這個 class 會在螢幕寬度 767 以下時，將選單 `display: none;`

所以應該要把選單的 visible-desktop class 移除

**Comment by thewayiam** [comment]
為了 [網友回報的令一個問題](https://groups.google.com/d/msg/g0v-ly/uzC3c_Nxo44/kBnIhXaRDwAJ)
問題：
手機頁面除了字會變直的顯示之外，有些按鍵會重疊就沒辦法點擊，點擊[立委選舉得票狀況] 都會連去[找法案]或[找表決]
所以暫時加了visible-desktop這個不太好的處理，歡迎PR
