### ISSUE TITLE
立委屆別選單 URL 錯誤

### ISSUE THREAD

**Issue by jyyan** [g0v/twly-voter-guide#50]
[參考頁面](http://vote.ly.g0v.tw/legislator/county/%E8%87%BA%E5%8C%97%E5%B8%82/)
下方點選**第八屆** 的超連結會連回當前的第九屆，

但參考第七屆的URL 直接改參數輸入 [URL](http://vote.ly.g0v.tw/legislator/county/%E8%87%BA%E5%8C%97%E5%B8%82/8/) 可以正常訪問地八屆立委的資料

**Comment by thewayiam** [comment]
感謝提醒！標註出要改的地方，這個 issue 還算蠻好解的，歡迎來哦，有問題可以討論，來吧
https://github.com/g0v/twly-voter-guide/blob/master/legislator/templates/legislator/county.html#L17

**Comment by jyyan** [comment]
感謝協助提示需要修改的 template
