### ISSUE TITLE
the srcret_key setting must not be empty

### ISSUE THREAD

**Issue by 1135727654** [g0v/twly-voter-guide#54]
How can I solve it?
![qq 20170330162757](https://cloud.githubusercontent.com/assets/26155462/24494833/df96ff4e-1565-11e7-94d9-6d62585a9913.png)

**Comment by thewayiam** [comment]
check this file /ly/local_settings.py
sample file didn't set anything in it (https://github.com/g0v/twly-voter-guide/blob/master/ly/local_settings.sample.py#L13)
please input some random letter or remove this line, then it will use the default one(https://github.com/g0v/twly-voter-guide/blob/master/ly/settings.py#L12)
