### ISSUE TITLE
after ptyhon

### ISSUE THREAD

**Issue by 1135727654** [g0v/twly-voter-guide#55]
who can help me
![qq 20170331101025](https://cloud.githubusercontent.com/assets/26155462/24533450/660359d0-15fa-11e7-8a8d-8f6bb41bed86.jpg)
![qq 20170331101034](https://cloud.githubusercontent.com/assets/26155462/24533451/660d7f82-15fa-11e7-8308-299693a8bffe.jpg)

**Comment by 1135727654** [comment]
after python manage.py runserver 
what should I do

**Comment by thewayiam** [comment]
Please run `pip install django-debug-toolbar==1.5` on your virtualenv, or pull this repo again and `pip install -r requirements.txt`

**Comment by 1135727654** [comment]
thank you for help
