### ISSUE TITLE
why I can't open the list?

### ISSUE THREAD

**Issue by 1135727654** [g0v/twly-voter-guide#56]
![111](https://cloud.githubusercontent.com/assets/26155462/24534837/fc8604c2-1602-11e7-849a-79ba4782d00b.png)

**Comment by thewayiam** [comment]
Those two dropdown will open automaticlly when mouse hover, don't need to click, [related code](https://github.com/g0v/twly-voter-guide/blob/master/templates/base.html#L163-L169), right now if you click it will be abnormal and need to click again to get normal again, it's kind of a bug but I don't have a clue to fix it.
you could check their behavior on [prodction site](http://vote.ly.g0v.tw/)
