### ISSUE TITLE
could not connect to database template1 

### ISSUE THREAD

**Issue by 1135727654** [g0v/twly-voter-guide#57]
![22](https://cloud.githubusercontent.com/assets/26155462/24542107/f0bd058a-162c-11e7-883e-65d90a12e50c.png)

**Comment by thewayiam** [comment]
You need to specify username as [README](https://github.com/g0v/twly-voter-guide#restore-data-into-database), [database user password setup](https://github.com/g0v/twly-voter-guide#in-ubuntu-1204-lts) also needed.
If setup procedure too annoying, you could try [docker](https://github.com/g0v/twly-voter-guide#install-docker-and-docker-compose)
