### ISSUE TITLE
UnicodeEncodeError at/bill/

### ISSUE THREAD

**Issue by 1135727654** [g0v/twly-voter-guide#58]
当我点‘找法案’的时候就出现了错误 我要怎么改
![11](https://cloud.githubusercontent.com/assets/26155462/24549089/5c240432-164a-11e7-9715-21eda65e2299.png)
![22](https://cloud.githubusercontent.com/assets/26155462/24549094/5fdde5fc-164a-11e7-91de-54cc8dd98697.png)

**Comment by thewayiam** [comment]
I can't reproduce this error, if you already follow through README, you might want to check your database or elasticsearch encoding settings.
What's your ubuntu version?

**Comment by 1135727654** [comment]
我还是不知道怎么改

**Comment by thewayiam** [comment]
I still don't know your ubuntu version, have you see any error while run [this command](https://github.com/g0v/twly-voter-guide#build-elasticsearch-index)

**Comment by maxinezxy** [comment]
怎么改怎么改怎么改

**Comment by thewayiam** [comment]
have you see any error while run [this command](https://github.com/g0v/twly-voter-guide#build-elasticsearch-index)

**Comment by 1135727654** [comment]
I use docker, I don't know why this mistake

**Comment by 1135727654** [comment]
while I run 'python manage.py rebuild_index' this command
![v r8u5qixbbdk 1n2dnz8 4](https://cloud.githubusercontent.com/assets/26155462/25938308/588f36fc-3661-11e7-8cd1-d9daed49826d.jpg)

**Comment by thewayiam** [comment]
As error message shows, your elasticsearch service didn't start, run `sudo service elasticsearch start` to start the service.
Are you using docker? if docker is used, you should run `docker-compose run django python manage.py rebuild_index` instead of `python manage.py rebuild_index`, it seems you didn't start docker, your django error message of python version it's not the docker settings.

**Comment by 1135727654** [comment]
There will still be errors

**Comment by thewayiam** [comment]
What's the error message when you run `sudo service elasticsearch start` ?
What message when you run `curl localhost:9200` ?

**Comment by maxinezxy** [comment]
![11](https://cloud.githubusercontent.com/assets/24729131/25990630/fc4154a2-3732-11e7-9736-703d255f4b4c.jpg)

**Comment by thewayiam** [comment]
It seems you didn't install elasticsearch, please follow through [README](https://github.com/g0v/twly-voter-guide#install-elasticsearch) or using [docker](https://github.com/g0v/twly-voter-guide#install-docker-and-docker-compose), if your didn't follow README environment, I can't help setup of everyone with their different environment, don't waste both our time.

**Comment by maxinezxy** [comment]
我很确信我当时安装了elasticsearch，但是为什么其他都没有问题 就只有bill这个页面出错

**Comment by thewayiam** [comment]
Only some pages need to access elasticsearch, bill is one of them.
If elasticsearch started, `curl localhost:9200` shows something like this:
```
{
 "status" : 200,
 "name" : "Storm",
 "version" : {
   "number" : "1.3.1",
   "build_hash" : "2de6dc5268c32fb49b205233c138d93aaf772015",
   "build_timestamp" : "2014-07-28T14:45:15Z",
   "build_snapshot" : false,
   "lucene_version" : "4.9"
 },
 "tagline" : "You Know, for Search"
}
```
So please make sure elasticsearch setup didn't appear any error message, or use docker as above.

**Comment by maxinezxy** [comment]
ok，I will try again

**Comment by maxinezxy** [comment]
![qq 20170517154920](https://cloud.githubusercontent.com/assets/24729131/26143676/79d9a6d8-3b18-11e7-936c-9e0930dd6912.png)
![qq 20170517154928](https://cloud.githubusercontent.com/assets/24729131/26143684/7fc6b004-3b18-11e7-810b-e06cac8eb792.jpg)

**Comment by maxinezxy** [comment]
![qq 20170517154920](https://cloud.githubusercontent.com/assets/24729131/26145051/a20fa242-3b1d-11e7-97ec-7a910cee9da5.png)
![qq 20170517154928](https://cloud.githubusercontent.com/assets/24729131/26145060/a9612af2-3b1d-11e7-84bf-05ac0b953d49.jpg)

**Comment by maxinezxy** [comment]
![qq 20170517154920](https://cloud.githubusercontent.com/assets/24729131/26146510/028db596-3b23-11e7-9f8f-f6a2b7dfe2ff.png)
![5geugpm4jvlrw xg9f 8 c9](https://cloud.githubusercontent.com/assets/24729131/26146517/06c9c8de-3b23-11e7-95a9-72a2538e7245.jpg)

**Comment by thewayiam** [comment]
as error message, port 5432 already used in your local machine, you need to stop your service or change to a port you didn't used.

**Comment by maxinezxy** [comment]
我改好了 只要把编码方式改成UTF8就不会出错了
